# Generated by Django 2.1.3 on 2019-04-29 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acara',
            fields=[
                ('id_acara', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('tgl_mulai', models.DateField()),
                ('tgl_akhir', models.DateField()),
                ('is_free', models.BooleanField()),
            ],
            options={
                'db_table': 'ACARA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('no_kartu', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('saldo', models.FloatField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ANGGOTA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id_laporan', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('datetime_pinjam', models.DateTimeField()),
                ('nomor_sepeda', models.CharField(max_length=10)),
                ('id_stasiun', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'LAPORAN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('ktp', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('tgl_lahir', models.DateField()),
                ('no_telp', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'PERSON',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sepeda',
            fields=[
                ('nomor', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('merk', models.CharField(max_length=10)),
                ('jenis', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'SEPEDA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stasiun',
            fields=[
                ('id_stasiun', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('alamat', models.TextField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('nama', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'STASIUN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id_voucher', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=255)),
                ('nilai_poin', models.FloatField()),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'VOUCHER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AcaraStasiun',
            fields=[
                ('id_stasiun', models.ForeignKey(db_column='id_stasiun', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='registrasi.Stasiun')),
            ],
            options={
                'db_table': 'ACARA_STASIUN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('no_kartu_anggota', models.ForeignKey(db_column='no_kartu_anggota', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='registrasi.Anggota')),
                ('datetime_pinjam', models.DateTimeField()),
                ('datetime_kembali', models.DateTimeField(blank=True, null=True)),
                ('biaya', models.FloatField(blank=True, null=True)),
                ('denda', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PEMINJAMAN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('ktp', models.ForeignKey(db_column='ktp', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='registrasi.Person')),
                ('gaji', models.FloatField()),
            ],
            options={
                'db_table': 'PETUGAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('no_kartu_anggota', models.ForeignKey(db_column='no_kartu_anggota', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='registrasi.Anggota')),
                ('date_time', models.DateTimeField()),
                ('jenis', models.CharField(max_length=20)),
                ('nominal', models.FloatField()),
            ],
            options={
                'db_table': 'TRANSAKSI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Penugasan',
            fields=[
                ('ktp', models.ForeignKey(db_column='ktp', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='registrasi.Petugas')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'PENUGASAN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransaksiKhususPeminjaman',
            fields=[
                ('no_kartu_anggota', models.ForeignKey(db_column='no_kartu_anggota', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='registrasi.Transaksi')),
                ('date_time', models.DateTimeField()),
                ('datetime_pinjam', models.DateTimeField(blank=True, null=True)),
                ('no_sepeda', models.CharField(blank=True, max_length=10, null=True)),
                ('id_stasiun', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'TRANSAKSI_KHUSUS_PEMINJAMAN',
                'managed': False,
            },
        ),
    ]
